import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/layouts/header";
import { Toaster } from "react-hot-toast";
import ReactQueryProviders from "@/Providers/ReactQueryProvider";
import { Poppins } from 'next/font/google'; 

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-poppins"

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <ReactQueryProviders>
           <main>
          <Toaster/>
          <Header />
                  {children}

        </main>
        </ReactQueryProviders>
       
      </body>
    </html>
  );
}
